# Generated by Django 2.1.3 on 2018-11-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
