# Generated by Django 2.1.3 on 2018-12-02 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20181129_2044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='community_page',
            new_name='website',
        ),
    ]
