# Generated by Django 2.1.3 on 2018-12-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default='4', max_digits=2),
        ),
    ]
