# Generated by Django 2.1.3 on 2018-12-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.CharField(default='', max_length=150),
        ),
    ]
