# Generated by Django 2.1.3 on 2018-12-11 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20181211_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.DecimalField(decimal_places=0, default='4', max_digits=1),
        ),
    ]
