# Generated by Django 2.1.3 on 2018-12-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20181211_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.CharField(choices=[('1', 'Once / Gift'), ('2', 'Twice Yearly'), ('3', 'Once every three months'), ('4', 'Once every 4 months'), ('5', 'Once every two months')], default=4, max_length=300),
        ),
    ]
