# Generated by Django 2.1.3 on 2018-12-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20181211_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.CharField(choices=[('Once / Gift', 'Once / Gift'), ('Twice Yearly', 'Twice Yearly'), ('Once every 3 months', 'Once every 3 months'), ('Once every 4 months', 'Once every 4 months'), ('Once every 2 months', 'Once every 2 months')], default=4, max_length=300),
        ),
    ]
